### ISSUE TITLE
mvnd version support Maven 3.9.6+

### ISSUE THREAD

**Issue by gsmet** [apache/maven-mvnd#1009]
Hi,

Quarkus is not yet compatible with Maven 4 (and it will probably require some major work on our side) so we stick to Maven 3.9.x.

To my knowledge, Maven 3.9.6 is the first version to actually support Maven plugins compiled with Java 17. Even if Quarkus 3.7+ requires Java 17, we are still compiling the Maven plugins with Java 11 compatibility due to that so that people don't have to update to very latest Maven.
But we would like to change that as the error message you obtain when using Java 11 is very confusing.

Problem is: mvnd has become a critical part of our workflow for some of us and we would need a mvnd version based on Maven 3.9.6+.

Are there any new versions planned that would update Maven 3.9.x?

Thanks!

**Comment by gnodet** [comment]
Yes, we're planning a mvnd release based on upcoming Maven 3.9.8.

**Comment by gsmet** [comment]
Thanks, that's awesome. No need to keep this issue open then.
