### ISSUE TITLE
No asset was released at v1.0.2

### ISSUE THREAD

**Issue by suzuki-shunsuke** [apache/maven-mvnd#1109]
No asset was released at v1.0.2.

https://github.com/apache/maven-mvnd/releases/tag/1.0.2

<img width="255" alt="image" src="https://github.com/user-attachments/assets/34adc631-980f-48b6-bb72-c8199d8e8a8b">

**Comment by suzuki-shunsuke** [comment]
The release workflow succeeded.

https://github.com/apache/maven-mvnd/actions/runs/10479803359/job/29026496043

```
Run actions/upload-release-asset@v1
  with:
    upload_url: https://uploads.github.com/repos/apache/maven-mvnd/releases/17116[2](https://github.com/apache/maven-mvnd/actions/runs/10479803359/job/29026496043#step:12:2)843/assets{?name,label}
    asset_path: mvnd-linux-amd6[4](https://github.com/apache/maven-mvnd/actions/runs/10479803359/job/29026496043#step:12:4)/maven-mvnd-1.0.2-linux-amd64.tar.gz
    asset_name: maven-mvnd-1.0.2-linux-amd64.tar.gz
    asset_content_type: application/x-gzip
  env:
    JAVA_VERSION: 22
    JAVA_HOME: /opt/hostedtoolcache/Java_Zulu_jdk/22.0.2-9/x[6](https://github.com/apache/maven-mvnd/actions/runs/10479803359/job/29026496043#step:12:6)4
    JAVA_HOME_22_X64: /opt/hostedtoolcache/Java_Zulu_jdk/22.0.2-[9](https://github.com/apache/maven-mvnd/actions/runs/10479803359/job/29026496043#step:12:9)/x64
    VERSION: 1.0.2
    GITHUB_TOKEN: ***
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-[10](https://github.com/apache/maven-mvnd/actions/runs/10479803359/job/29026496043#step:12:10)-11-github-actions-deprecating-save-state-and-set-output-commands/
```

**Comment by cstamas** [comment]
Dang, seems I messed up the release process...

Nevertheless, downloads are here:
https://downloads.apache.org/maven/mvnd/1.0.2/

**Comment by suzuki-shunsuke** [comment]
Thank you for replying quickly.
Oh, our tool installs maven-mvnd from GitHub Releases. 
We'll consider installing it from the URL.

**Comment by suzuki-shunsuke** [comment]
> We'll consider installing it from the URL.

Done.

- https://github.com/aquaproj/aqua-registry/pull/26230
- https://github.com/aquaproj/aqua-registry/releases/tag/v4.217.0

**Comment by cstamas** [comment]
In the meantime, I updated the release (uploaded assets). Still, the "official" way to download Apache Maven binaries is thru https://downloads.apache.org/maven/ (while some of them are available from Maven Central as well, but mvnd for example is not)
