### ISSUE TITLE
err in my code! why

### ISSUE THREAD

**Issue by Hepengzhou** [apache/maven-mvnd#1123]
java.lang.NoSuchMethodError: 'org.apache.maven.execution.MavenExecutionRequest org.apache.maven.execution.MavenExecutionRequest.setIgnoreTransitiveRepositories(boolean)'
![image](https://github.com/user-attachments/assets/986bb045-a057-4b36-a2a8-0fa412ba2bf1)

**Comment by Hepengzhou** [comment]
java.lang.NoSuchMethodError: 'org.apache.maven.execution.MavenExecutionRequest org.apache.maven.execution.MavenExecutionRequest.setIgnoreTransitiveRepositories(boolean)'

**Comment by ppalaga** [comment]
No stack trace in your code! Why

**Comment by Hepengzhou** [comment]
"What should I do to see the results? I ran 'mvnd clean' in the command prompt (cmd), but nothing has changed."
