### ISSUE TITLE
withMaven: downstreamPipelineTriggerRunListener - Skip triggering downstream pipeline - version is same

### ISSUE THREAD

**Issue by heamnthnhk11** [apache/maven-mvnd#1153]
0

I two repositories Upstream project-A & downstream project-B, B build is triggered when A build is success on Jenkins. If there is a commit on release-Test1 branch on A, it will trigger the job on jenkins job-A due to SCM changes. Once the release-Test1 on A job is done, it will trigger the release-Test1 on B job.

Problem : If make few more commits on release-Test1 on A, it will trigger the A job on Jenkins due to SCM changes, but after A-build success Job-B relase-Test1 is not triggering. It shows the error as follows: [withMaven] downstreamPipelineTriggerRunListener - Skip triggering downstream pipeline B_MAIN-MODULE-BUILD-PIPELINE_seeded » release-Test1 as it was already triggered for Maven dependencies: net.mike.slate:Project-A:zip:src:Test1(Test1)

I'm using the following script to trigger downstream jobs:

// Downstream triggers
					options:
						[
						pipelineGraphPublisher 
							(
							includeSnapshotVersions: false,
							includeReleaseVersions: true,
							includeScopeCompile: true,
							includeScopeRuntime: true,
							includeScopeProvided: true,
							includeScopeTest: false,
							lifecycleThreshold: MAVEN_DOWNSTREAM_TRIGGER_LIFECYCLE
							triggerWithSameVersion: true
							)
						]

Even I use lifecycleThreshold as install or deploy, it doesn't work.

I want whenever the release-Test1 on A is triggered and build got success, it has to trigger Test1 on B, even it is the same version release.

**Comment by ppalaga** [comment]
This sounds like an issue with your CI rather than with Maven or mvnd. I do not think we can help.
