### ISSUE TITLE
[discuss]`maven.version` conflict in pom.xml & system property

### ISSUE THREAD

**Issue by lanmaoxinqing** [apache/maven-mvnd#516]
We have the `maven.version` property configed in root `pom.xml`, to specify the base maven version we used for mvnd.
```
    <properties>
        <maven.version>3.8.1</maven.version>
    </properties>

```

And we also setup this property in `DaemonMavenCli.java`,   for `--version` usage to display system maven version, i guess?
```
        String mavenVersion = buildProperties.getProperty(CLIReportingUtils.BUILD_VERSION_PROPERTY);
        systemProperties.setProperty("maven.version", mavenVersion);
```

It works fine in each designed satuation, until i try to use `maven.version` in `xxx.proerties` files. `maven.version` defined in `pom.xml` is overrided by system property, according to [Spring Externalized Configuration](https://docs.spring.io/spring-boot/docs/2.0.6.RELEASE/reference/html/boot-features-external-config.html), so i can't get the maven version we use for mvnd.

Is this an expected feature, or a bug ?

**Comment by ppalaga** [comment]
> It works fine in each designed satuation, until i try to use `maven.version` in `xxx.proerties` files. 

Which `xxx.properties` files do you mean?

> `maven.version` defined in `pom.xml`

Which `pom.xml`? 

 is overrided by system property, according to [Spring Externalized Configuration](https://docs.spring.io/spring-boot/docs/2.0.6.RELEASE/reference/html/boot-features-external-config.html), so i can't get the maven version we use for mvnd.

Not sure at all, how Spring Externalized Configuration comes into game? 
Could you perhaps use an example to explain what you mean?

**Comment by lanmaoxinqing** [comment]
Oh, sorry for my ambiguously description. I'm aim to build custom mvnd with different maven versions, so i'd like to specify different daemon registry path for each maven version.

Let's show the test code first...
https://github.com/lanmaoxinqing/mvnd/commit/f2426a834b42a4a25cf5e564bb7987b892da1933

Here is the github action result
https://github.com/lanmaoxinqing/mvnd/actions/runs/1466173659

Download the zip and go into `mvnd-0.7.1-SNAPSHOT-linux-amd64.jar:/mvn/lib/ext/mvnd-common-0.7.1-SNAPSHOT.jar:/org/mvndaemon/mvnd/common/build.properties`, you will find the `mvnVersion` is `3.6.3`, and the value i expect is `3.8.3`

Here is the detail below:

> Which pom.xml?

https://github.com/mvndaemon/mvnd/blob/85e4d0cf2a6c6de3c34a12c582c96ba0aa4a0baa/pom.xml#L49

> Which xxx.properties files do you mean?

https://github.com/mvndaemon/mvnd/blob/85e4d0cf2a6c6de3c34a12c582c96ba0aa4a0baa/common/src/main/resources/org/mvndaemon/mvnd/common/build.properties#L22

I try to add a property named `mvnVersion` after it using `maven.version` property defined in `pom.xml`

```
mvnVersion=${maven.version}
```


> how Spring Externalized Configuration comes into game?

https://github.com/mvndaemon/mvnd/blob/85e4d0cf2a6c6de3c34a12c582c96ba0aa4a0baa/daemon/src/main/java/org/apache/maven/cli/DaemonMavenCli.java#L1438-L1443

`maven.version` property is also defined in system property, and overrides the same property in `pom.xml`.

When i build mvnd with maven 3.6.3 and `maven.version` defined in `pom.xml` is `3.8.3`, the `mvnVersion` finally i get is `3.6.3`, rather than `3.8.3`.
