### ISSUE TITLE
Improve the doc text of `mvnd.pluginRealmEvictPattern` option

### ISSUE THREAD

**Issue by ppalaga** [apache/maven-mvnd#533]
From the current text https://github.com/mvndaemon/mvnd/blob/4bb5c5d5b533938d7710eeb08ac1aff5800e29d5/common/src/main/java/org/mvndaemon/mvnd/common/Environment.java#L253-L256 it is not clear how to use the option. An example would help. The option says it is a regexp, but based on https://github.com/gnodet/mvnd/commit/9ed8647014c311e5711bb8c40afa7f6abc4ea5f4#diff-e65744bdec30df4a8c9692d35f97c28fef1e81af93a54a3d0dbf5f0a8e8abd88R246 it seems to be that glob is the default.

**Comment by gnodet** [comment]
@ppalaga let me know if the doc seems understandable enough or if I should add more.
