### ISSUE TITLE
Refactor build & release workflow

### ISSUE THREAD

**Issue by aalmiray** [apache/maven-mvnd#542]
Looks like https://github.com/apache/maven-mvnd/blob/master/.github/workflows/verify.yaml has a lot of duplicated setup.

Would the team be interested in refactoring build & releases to use JReleaser? Here's for example how kcctl performs its releases (using the jreleaser-maven-plugin) publishing to sdkman and homebrew as well

**configuration**
https://github.com/kcctl/kcctl/blob/c0c6e473264da93fddd491fd9e28fb85fb5b9a22/pom.xml#L399-L458

**workflow**
https://github.com/kcctl/kcctl/blob/main/.github/workflows/release.yml

I can help setting up the code. Happy to discuss ideas 😄

**Comment by hboutemy** [comment]
notice that we'll need to follow Apache release rules = have a formal vote for 72h before shipping the release (or not if the vote does not pass)
is it feasible?

**Comment by hboutemy** [comment]
great, thank you
FYI, I just created #543 for the requirements after switch to Apache: there is both flexibility on details but some strict release requirements

**Comment by aalmiray** [comment]
Excellent @hboutemy! Happy to discuss which areas of the existing Apache Maven release process could be automated with JReleaser with its current feature set, or if something new were to be required we can figure out a way to add it to JReleaser.

**Comment by ppalaga** [comment]
> Would the team be interested in refactoring build & releases to use JReleaser?

+100 from me :)

**Comment by aalmiray** [comment]
@hboutemy @ppalaga excellent! How should we proceed? Discussing ideas on the mailing list or using this space?

**Comment by gnodet** [comment]
I wasn't aware of JReleaser, but this looks very promising.  I think we can continue using this space to discuss things.

**Comment by hboutemy** [comment]
let's start by describing what are the requirements for mvnd:
- ASF source-release archive published to Apache dist area (svn) after 72h vote by email on dev@maven #543 
- issue tracking is done with GitHub
- no convenience binaries published to Maven Central 
- other convenience binaries? published where?

**Comment by aalmiray** [comment]
Correct. We must follow the Apache Maven release process, which means IF convenience binaries are to be posted it must happen after a release vote has been successful. However before or after the vote is done the project has the _choice_ of posting a Git release with changelog.

1. If the Git release is posted BEFORE the vote then if **must** be set as a prerelease (in GitHub terms) and have **no** convenience binary assets. If the vote is canceled or fails then the Git release is dropped. If the vote is successful then the Git release is moved to final and convenience binaries _could_ be uploaded as release assets.

2. If the Git release is posted AFTER the vote passes then it _could_ contain convenience binaries as release assets.

These 2 options are a matter of process. The JReleaser tool can help creating the Git releases and uploading the release assets when needed.

Now, there's also the matter of shipping convenience binaries for snapshot releases only, such as on every push to a particular branch. Here the JReleaser tool also helps but then again the team should decide if this is worth adding and according to the rules.

Final convenience binaries (that is, non snapshots) may be posted to additional distribution channels and package managers such as:

Only require a Git repository, GitHub being the preferred option:
- Homebrew
- Gofish
- Macports
- Scoop

Require a username/password owned by the mvnd team on the given build service associated with the packager:
- Chocolatey
- Snapcraft
- Docker
- Fedora COPR

All platform packagers are optional. You can pick an choose which ones you'd want to use or none at all.

**Comment by ppalaga** [comment]
As for 1. vs. 2., if a GH release is the only way how to publish the changelog before publishing the binaries, then 1. sounds preferable. It is useful for the voters to read the changelog before they vote and possibly decide based on the information from the changelog.

> Now, there's also the matter of shipping convenience binaries for snapshot releases only, such as on every push to a particular branch. Here the JReleaser tool also helps but then again the team should decide if this is worth adding and according to the rules.

There is something like that in the current GH Actions workflow: the ZIPs for the infividual platforms are stored as the given Workflow execution's artifacts. See e.g. here in a recent successful build: 
https://github.com/apache/maven-mvnd/actions/runs/1648385567
![image](https://user-images.githubusercontent.com/1826249/148187940-d1464948-8d15-464b-b684-33eeccedb244.png)
The community members voting about a release can use these to manually test the release and adjust their vote based on that.

**Comment by aalmiray** [comment]
I'm not sure if 1. is the only way to provide a changelog, for example other Apache Maven projects rely on grabbing the list of issues from JIRA. If mvnd does not rely on JIRA and prefers the use of GitHub issues then yes, calculating the changelog in this way would be useful.

> There is something like that in the current GH Actions workflow
Correct, which is why I suggested it. JReleaser may be used to upload early-access and final binaries with the same configuration file/DSL.

**Comment by ppalaga** [comment]
> JReleaser may be used to upload early-access and final binaries with the same configuration file/DSL.

Where would JReleaser upload the early-access bineries? - to GH downloads area (same as final binaries) or to GH Actions job area (like we do currently?)

**Comment by aalmiray** [comment]
By default, as release assets on the Git release marked as `prerelease`, such as https://github.com/jreleaser/jreleaser/releases/tag/early-access. This would be the GH download area.

You have the option to additionally upload assets to S3, Artifactory, or an Http(s) server of your choice.

**Comment by aalmiray** [comment]
Correct. However this is not a JReleaser thing per se. If you're building binaries on GitHub actions you must run the workflow with different runners. You have the choice to upload build artifacts as part of the job. The default storage lifetime is set to 90 days.

You'd definitely want to upload artifacts to collect all of them before an early access release. This is what kcctl does. As a result you get artifacts in the job and in the Git release

https://github.com/kcctl/kcctl/actions/runs/1641712692
https://github.com/kcctl/kcctl/blob/main/.github/workflows/early-access.yml

**Comment by ppalaga** [comment]
> As a result you get artifacts in the job and in the Git release

This sounds good, thanks!

**Comment by aalmiray** [comment]
Should I prepare a PR to tackle both scenarios? We can of course keep discussing the approaches to take once you see how it would play out.

**Comment by ppalaga** [comment]
> Should I prepare a PR to tackle both scenarios?

Thanks, that would be highly welcome, at least from my side.

**Comment by aalmiray** [comment]
I've added a PR as a starting point https://github.com/apache/maven-mvnd/pull/574

**Comment by johanjanssen** [comment]
If you want to integrate the Chocolatey build, I'm currently maintaining it at https://github.com/johanjanssen/ChocolateyPackages/tree/master/mvndaemon. But we can copy/move it to the mvndaemon repo. Then all you need is a Chocolatey account and I can add it as a maintainer so it can be used to push new packages.

**Comment by aalmiray** [comment]
Given that Apache releases are always in source form, convenience binaries and packagers (at least for final releases) could continue to live under the `mvndaemon` owner/org. 

If so then updates to the `mvndaemon/homebrew-mvnd` repo may be needed as JReleaser takes care of most of the work. Similarly, it can generate the Chocolatey nuget and push it to the upstream repo. 

@ppalaga WDYT?
@johanjanssen would you consider donating/moving your choco package to the `mvnddaemon` repo?

**Comment by johanjanssen** [comment]
@aalmiray Yes you can have it if you want, I don't mind where you store it :).

**Comment by ppalaga** [comment]
+1 for moving to mvndaemon org. Please let me know if anybody of you wants some permissions there.

**Comment by johanjanssen** [comment]
I can't move the entire repository https://github.com/johanjanssen/ChocolateyPackages as it contains other Chocolatey packages. So I think the easiest way to move forward is if someone who has access to the target repository copies the mvnd directory https://github.com/johanjanssen/ChocolateyPackages/tree/master/mvndaemon from my repository.

Alternatively, I could also create a pull request if you tell me in which repo and directory this should be stored. As I noticed the homebrew is still in https://github.com/mvndaemon.

**Comment by aalmiray** [comment]
Ideally the choco package will be created using the JReleaser template mechanism. This means the default template would likely have to be updated to follow @johanjanssen's existing customizations. The crux of the transfer is the choco account which is current owned by @johanjanssen.

**Comment by johanjanssen** [comment]
> The crux of the transfer is the choco account which is current owned by @johanjanssen.

That can be solved quite easily if one of you creates a Chocolatey account that will be used by JReleaser, then I can give that account permissions to push packages to the Chocolatey repo.

**Comment by ppalaga** [comment]
> Ideally the choco package will be created using the JReleaser template mechanism.

Do we need a new mvnd-choco git repository under mvndaemon org for that?

**Comment by aalmiray** [comment]
> Do we need a new mvnd-choco git repository under mvndaemon org for that?

Yes. It could be created by hand or let JReleaser do it, in which case I'd look like this https://github.com/jreleaser/chocolatey-bucket/

**Comment by ppalaga** [comment]
I have created https://github.com/mvndaemon/mvnd-chocolatey and invited aalmiray and johanjanssen as admins

**Comment by aalmiray** [comment]
@ppalaga thanks! What we need is a choco API key to push the choco package to their registry. @johanjanssen has successfully pushed 5 versions of the mvndaemon choco package https://community.chocolatey.org/packages/mvndaemon#versionhistory

What we need to discuss is:
- package name: should it stay as `mvndaemon` or move to `mvnd`?
- the choco API key is required as a secret on this repository (JReleaser needs it) and the `mvndaemon/mvnd-chocolatey` repository. @johanjanssen has admin access to set secrets on the later but not on the first.
  - @johanjanssen could send his key to @ppalaga or @gnodet to set it as a secret on this repo.
  - OR a completely new choco account & API key created by @ppalaga / @gnodet used on both repos.

**Comment by johanjanssen** [comment]
Please create a new account/key. As I'm using mine for a lot more Chocolatey packages such as OpenJDK/Temurin... I don't think it's a good idea to share the existing key from a security perspective :).

**Comment by ppalaga** [comment]
> package name: should it stay as mvndaemon or move to mvnd?

I'd vote for `mvnd`.

>  a completely new choco account & API key created by @ppalaga / @gnodet used on both repos.

+1 for that, but I have close to zero time for that in coming two weeks.

**Comment by aalmiray** [comment]
OK. We can configure the choco package later.
