### ISSUE TITLE
create Apache source-release distribution archive

### ISSUE THREAD

**Issue by hboutemy** [apache/maven-mvnd#543]
now that mvnd is imported at Apache, we'll need its future releases to be published in Maven's dist area: https://archive.apache.org/dist/maven/

and of course follow Apache rules about voting a release candidate for 72h before pushing out the result if vote is positive

notice that I don't absolutely mean that we need to stick exactly with what is done on usual release process for all Maven parts: https://maven.apache.org/developers/release/maven-project-release-procedure.html
For example we're not forced to publish something to https://repository.apache.org/ given it seems nothing is published to Central https://repo.maven.apache.org/maven2/org/mvndaemon
There is also a question if switching `org.mvndaemon.mvnd` groupid to `org.apache.maven.mvnd` make sense or creates issues

@gnodet @olamy @ppalaga

**Comment by ppalaga** [comment]
> There is also a question if switching `org.mvndaemon.mvnd` groupid to `org.apache.maven.mvnd` make sense or creates issues

Nothing comes to my mind that should prevent it. We need to try and see whether it will really work.

**Comment by hboutemy** [comment]
and can you confirm nothing requires to be published to Maven Central?

**Comment by ppalaga** [comment]
> and can you confirm nothing requires to be published to Maven Central?

Yes, we never released anything to Central. The zipped distro distributed via GH downloads is currently the only distribution channel. Of course, this may change if we see a need.

**Comment by gnodet** [comment]
Done with https://github.com/apache/maven-mvnd/blob/master/.github/workflows/release.yaml#L70-L102
