### ISSUE TITLE
mvnd maven plugin

### ISSUE THREAD

**Issue by zundaren** [apache/maven-mvnd#546]
Is it possible to develop a mvnd maven plugin, which can be used after importing it in pom.xml

**Comment by gnodet** [comment]
Could you be a bit more specific, I don't really understand the question.

**Comment by zundaren** [comment]
similar <artifactId>maven-clean-plugin</artifactId> 
![image](https://user-images.githubusercontent.com/44863479/147650552-6c7fdae8-f53a-40ec-881e-c65a83a9db93.png)
ide can control process

**Comment by ppalaga** [comment]
If you want your IDE to use mvnd instead of mvn, then it cannot be reached by writing a plugin. You may still want to ask your IDE to implement such an option via their issue tracker.
