### ISSUE TITLE
How do i set other maven repository？

### ISSUE THREAD

**Issue by zhuxindong** [apache/maven-mvnd#549]
how do i set other maven repository？

**Comment by gnodet** [comment]
I don't understand the question.  Maven repositories are usually configured in the pom.

**Comment by Fzoss** [comment]
look https://github.com/apache/maven-mvnd/issues/553

**Comment by ppalaga** [comment]
> how do i set other maven repository？

The same way as with stock Maven https://maven.apache.org/guides/mini/guide-multiple-repositories.html
