### ISSUE TITLE
How to solve version declaration setting in pom.xml

### ISSUE THREAD

**Issue by reeeexchen** [apache/maven-mvnd#551]
When used mvnd to compile the project, but the dependency version declaration in parent pom.xml, such as [core-service] pom.xml only declaration the dependency without version, the mvnd seems not support.

**Comment by gnodet** [comment]
Can you set up a project to reproduce the problem ? It's not really clear from your description.

**Comment by gnodet** [comment]
Please reopen with more details if needed.
