### ISSUE TITLE
How to use mvnd in Jenkins?

### ISSUE THREAD

**Issue by ErQire** [apache/maven-mvnd#552]
How to use mvnd in Jenkins?

**Comment by yxxcrtd** [comment]
The same question !

I config Global Tool Configuration in jenkins, and set Maven's Name is **mvnd**, and MAVEN_HOME is **/home/mvnd-0.7.1/mvn**, then build without mvnd, hurry, thanks

**Comment by ErQire** [comment]
> 同样的问题！
> 
> 我在jenkins里配置了全局工具配置，设置Maven的名字是**mvnd**，MAVEN_HOME是**/home/mvnd-0.7.1/mvn**，然后build不用mvnd，快点，谢谢
Are you sure it works?

**Comment by ErQire** [comment]
> The same question !
> 
> I config Global Tool Configuration in jenkins, and set Maven's Name is **mvnd**, and MAVEN_HOME is **/home/mvnd-0.7.1/mvn**, then build without mvnd, hurry, thanks
Are you sure it works?

**Comment by gnodet** [comment]
I have it working by specifying a shell script to run instead of maven and using 
```
/usr/share/mvnd-0.7.1-linux-amd64/bin/mvnd install
```

**Comment by gnodet** [comment]
Another possibility, if you want to use the "high maven goals" maven jenkins configuration, is to point jenkins to your `mvnd` installation as a new maven (the name is up to you), and make sure to either rename or copy the `mvnd` executable to `mvn` in the mvnd home `bin` folder.
