### ISSUE TITLE
macOS  Monterey doesn't work with mvnd

### ISSUE THREAD

**Issue by yxxcrtd** [apache/maven-mvnd#554]

**Comment by yxxcrtd** [comment]
I config env in  .zshrc 
export PATH=$PATH:/Users/yxx/mvnd-0.7.1/bin

**Comment by yxxcrtd** [comment]
how to fix

**Comment by gnodet** [comment]
This has to be an environment issue, I do use Monterey without any problem.  Is the execute permission set on the executable ?

**Comment by yxxcrtd** [comment]
I don't known why maven can execute?

**Comment by gnodet** [comment]
> /Users/yxx/mvnd-0.7.1/bin

Have you tried setting the executable flag ?
```
chmod +x /Users/yxx/mvnd-0.7.1/bin/mvnd
```
and can you paste the output of 
```
ls -la /Users/yxx/mvnd-0.7.1/bin/
```

**Comment by yxxcrtd** [comment]
> > /Users/yxx/mvnd-0.7.1/bin
> 
> Have you tried setting the executable flag ?
> 
> ```
> chmod +x /Users/yxx/mvnd-0.7.1/bin/mvnd
> ```
> 
> and can you paste the output of
> 
> ```
> ls -la /Users/yxx/mvnd-0.7.1/bin/
> ```

It works!  tsk !!!
