### ISSUE TITLE
Let JVM set max heap size instead of a default value of 2GB (`mvnd.maxHeapSize`)

### ISSUE THREAD

**Issue by hashhar** [apache/maven-mvnd#560]
Have we considered making the `mvnd.maxHeapSize` config default to null so that the JVM can decide the max heap size instead of the current default of 2GB?

This will bring it in line with vanilla Maven which leaves the heap size to the JVM unless an explicit `-Xmx` is passed (either on command line, MAVEN_OPTS or other mechanisms listed on https://maven.apache.org/configure.html).

With current out-of-box behaviour of mvnd it's a bit frustrating to discover that the daemon is crashing because it is low on memory especially since the observable failure is the lost keepalives instead of an OOM.

(See https://github.com/apache/maven-mvnd/issues/291#issuecomment-1003319291 for more context)

cc: @gnodet created as requested.

I'll be happy to submit a patch if we can agree on some behavior here.

**Comment by ppalaga** [comment]
> making the `mvnd.maxHeapSize` config default to null so that the JVM can decide the max heap size instead of the current default of 2GB?

Sounds like a good idea. Thanks for reporting @hashhar!

**Comment by gnodet** [comment]
> Have we considered making the `mvnd.maxHeapSize` config default to null so that the JVM can decide the max heap size instead of the current default of 2GB?
> 
> This will bring it in line with vanilla Maven which leaves the heap size to the JVM unless an explicit `-Xmx` is passed (either on command line, MAVEN_OPTS or other mechanisms listed on https://maven.apache.org/configure.html).
> 
> With current out-of-box behaviour of mvnd it's a bit frustrating to discover that the daemon is crashing because it is low on memory especially since the observable failure is the lost keepalives instead of an OOM.
> 
> (See [#291 (comment)](https://github.com/apache/maven-mvnd/issues/291#issuecomment-1003319291) for more context)
> 
> cc: @gnodet created as requested.
> 
> I'll be happy to submit a patch if we can agree on some behavior here.

@hashhar I think not setting the max heap size sounds reasonable.  Do you want to provide a PR for that ?

**Comment by hashhar** [comment]
Thanks for the decision. I'll work on the PR over this weekend, expect it soon.

**Comment by cheneychoi** [comment]
@hashhar hey bro,i met the same situation ,is this issue solved?
