### ISSUE TITLE
I failed to execute MVND on MAC

### ISSUE THREAD

**Issue by Oliverwqcwrw** [apache/maven-mvnd#568]
mvnd-0.7.1-linux-amd64 that is my installed ,when I execute MVND ,show me "cannot execute binary file"

**Comment by gnodet** [comment]
> mvnd-0.7.1-linux-amd64 that is my installed ,when I execute MVND ,show me "cannot execute binary file"

What's the output of `uname -a` on your platform ?

**Comment by Oliverwqcwrw** [comment]
Darwin aolifu-2.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64

**Comment by Oliverwqcwrw** [comment]
I know, I should use this package 'mvnd-0.7.1-darwin-amd64'
