### ISSUE TITLE
I failed to execute 'mvnd -version' on my MAC

### ISSUE THREAD

**Issue by Oliverwqcwrw** [apache/maven-mvnd#569]
when I execute 'mvnd -version', the error is 

mvnd native client 0.7.1-darwin-amd64 (97c587c11383a67b5bd0ff8388bd94c694b91c1e)Terminal: org.jline.terminal.impl.PosixSysTerminal with pty org.jline.terminal.impl.jansi.osx.OsXNativePty
java.lang.NullPointerException: null

**Comment by gnodet** [comment]
Please run `rm -Rf ~/.m2/mvnd/registry/0.7.1`, run `mvnd -X -version`, report the output and report the content of the log files in the `~/.m2/mvnd/registry/0.7.1` directory.

**Comment by Oliverwqcwrw** [comment]
very thankful
