### ISSUE TITLE
并不快，对比了mvn 和mvnd的速度

### ISSUE THREAD

**Issue by Lvbuqing** [apache/maven-mvnd#575]
![d9437240f910e4f785a0e2c34249e45](https://user-images.githubusercontent.com/32841009/148638161-f2ad7fd0-ab70-4a53-a61a-234aa374ed99.jpg)
![33a021a19ea9da6b386e40b839c9e65](https://user-images.githubusercontent.com/32841009/148638175-72f96897-7572-4f5a-a62d-54d3de947168.jpg)
![bc0c5cf31990a529cef3eb8ac163f80](https://user-images.githubusercontent.com/32841009/148638177-c7205176-764d-4d76-814a-8adfefd866cd.jpg)
![28c33a67f6f7b89da5d4e517e79fd42](https://user-images.githubusercontent.com/32841009/148638180-dd5df89b-30cd-4c0c-bde0-910437cde674.jpg)

**Comment by Lvbuqing** [comment]
两边相差3秒钟，没有太大的区别

**Comment by NoSugarCoffee** [comment]
并不是并行构建就一定能加快速度，能你的项目结构等有一定关系, 建议阅读https://cwiki.apache.org/confluence/display/MAVEN/Parallel+builds+in+Maven+3

**Comment by NoSugarCoffee** [comment]
same as https://github.com/apache/maven-mvnd/issues/570

**Comment by Lvbuqing** [comment]
感谢你的回复，试过了打包好几次，打包时间还是没有变化才提的issues，另外，我这边的项目是传统项目，并没有什么其他的依赖

**Comment by gnodet** [comment]
@Lvbuqing could you please write the title and comments in English.  If you don't speak English, please use a translator, else we can't read.

**Comment by NoSugarCoffee** [comment]
> @Lvbuqing @NoSugarCoffee could you please write the title and comments in English. If you don't speak English, please use a translator, else we can't read.

@Lvbuqing said that compared with maven, mvnd could not make his project faster，I give him some advice like you replied in https://github.com/apache/maven-mvnd/issues/570 , this issue can be closed, I think
