### ISSUE TITLE
Local settings.xml results current folder used as repository

### ISSUE THREAD

**Issue by honnix** [apache/maven-mvnd#588]
For a reason, we have a valid `settings.xml` file under our project root folder. This file is not intended to be used by Maven when building and it is only meant to be packed into a container.

It seems `mvnd` will by default use that file, treat the folder where this file sits as `maven repository` root, and download artifacts to the folder. Is this an intended behaviour? Plain maven does not seem to be bothered by the existence of this file.

**Comment by honnix** [comment]
Tried using `mvnd -s .../.m2/settings.xml`, `mvn -gs .../.m2/settings.xml` and `mvn -Dmaven.settings=.../.m2/settings.xml`. But none of them works and the one in current folder is still being picked up.

Also tried making the `settings.xml` in the project root folder malformed, and that broke the build, which means it is indeed picked up.

**Comment by gnodet** [comment]
I think this is caused by https://github.com/apache/maven-mvnd/pull/573

**Comment by honnix** [comment]
@gnodet Thanks for the info. Do you mean it's caused by changes made in #573?

**Comment by gnodet** [comment]
> @gnodet Thanks for the info. Do you mean it's caused by changes made in #573?

No, I meant it's the same issue. This should already be fixed in the master branch if you can build it and give it a try to confirm, that would be awesome !

**Comment by honnix** [comment]
Aha, I see. I will give it a try later.

**Comment by honnix** [comment]
@gnodet I can confirm that the build from main branch fixes this issue. Thanks for the help! I'm closing this.
