### ISSUE TITLE
docker jenkins mvnd configured build error！

### ISSUE THREAD

**Issue by 501956430** [apache/maven-mvnd#589]
1、In container configuration information：
<img width="797" alt="截屏2022-01-21 10 31 07" src="https://user-images.githubusercontent.com/20204491/150455225-ebe3ecab-f851-4bcd-9ddf-262ccff63bb2.png">

2、jenkins build error：
<img width="1056" alt="截屏2022-01-21 10 33 24" src="https://user-images.githubusercontent.com/20204491/150455509-63f5be53-2fc1-4a91-af2e-10a3c989403a.png">

**Comment by gnodet** [comment]
It looks like if Jenkins is trying to run `mvn mvnd` which will obviously fail.
Please configure Jenkins correctly.
Also note that at this point, running `mvnd` inside a CI system is not really supported.

**Comment by 501956430** [comment]
@gnodet When to support?
