### ISSUE TITLE
When MVND is used to compile a project, the addClasspath parameter in the manifest of the configuration item compiled by maven-jar-plugin is invalid, and the class-path parameter is missing in the manifest. MF file in the compiled JAR package

### ISSUE THREAD

**Issue by wypro** [apache/maven-mvnd#590]
![image](https://user-images.githubusercontent.com/55936067/150463176-afec2c93-866b-4fca-8f63-2739a1fdbd27.png)
![FBMUMQDIXUIRI~C `%2$46R](https://user-images.githubusercontent.com/55936067/150463220-f62fe02b-2303-4a51-8096-e6b8510e90f0.png)

**Comment by gnodet** [comment]
Could you set up a small project to reproduce the issue please ?

**Comment by wypro** [comment]
> 你能建立一个小项目来重现这个问题吗？

Yes, please wait for me

**Comment by wypro** [comment]
> Could you set up a small project to reproduce the issue please ?
The address of the small project that recreates the problem.
Thank you. Best wishes.
https://github.com/wypro/mvnd-bug-demo

**Comment by gnodet** [comment]
Could you try specifying the latest `3.2.2` version on the `maven-jar-plugin` ? I can't really reproduce the problem locally and it seems to work with expliciting this version.

**Comment by wypro** [comment]
> Could you try specifying the latest `3.2.2` version on the `maven-jar-plugin` ? I can't really reproduce the problem locally and it seems to work with expliciting this version.

Thanks for reminding. After testing, it is confirmed that the problem is caused by the low version of Maven-jar-plugin. If the version is not specified, the project will be compiled using version 2.4 by default
