### ISSUE TITLE
 Update to latest maven 3.8.5?

### ISSUE THREAD

**Issue by MarkvanOsch** [apache/maven-mvnd#615]
Hi all, has anybody already planned to upgrade mvnd to the latest maven 3.8.5?

I see this commit to 3.8.4, but that seems not complete, or something else:
https://github.com/apache/maven-mvnd/commit/a9cf00066682095af519c8f949929f39f149b06a

Because on MacOS I see this output with the latest mvnd 0.7.1 version:

```
➜  ~ mvnd --version
mvnd native client 0.7.1-darwin-amd64 (97c587c11383a67b5bd0ff8388bd94c694b91c1e)
Terminal: org.jline.terminal.impl.PosixSysTerminal with pty org.jline.terminal.impl.jansi.osx.OsXNativePty
Apache Maven 3.8.3 (ff8e977a158738155dc465c6a97ffaf31982d739)
Maven home: /usr/local/Cellar/mvnd/0.7.1/libexec/mvn
Java version: 11.0.12, vendor: Homebrew, runtime: /usr/local/Cellar/openjdk@11/11.0.12/libexec/openjdk.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "12.3", arch: "x86_64", family: "mac"
```

**Comment by gnodet** [comment]
See https://github.com/apache/maven-mvnd/pull/616

**Comment by MarkvanOsch** [comment]
Thanks @gnodet , really like and enjoy the mvnd performance for my daily work, top!
