### ISSUE TITLE
Error occurred during initialization of VM , Could not reserve enough space for 2097152KB object heap

### ISSUE THREAD

**Issue by TOP-LH** [apache/maven-mvnd#644]
When I inputmvnd -v, I get an error, how do I fix it?

Screenshot
![image](https://user-images.githubusercontent.com/49888630/167240976-b4c5f0e3-6ee7-400d-84b1-587caeab2f66.png)

Log message
`Error occurred during initialization of VM ,
Could not reserve enough space for 2097152KB object heap
`

**Comment by gnodet** [comment]
Try modifying the `[MVND_HOME]/conf/mvnd.properties` to change the `mvnd.minHeapSize` and `mvnd.maxHeapSize` properties to proper values.  This has been for the next release already (see https://github.com/apache/maven-mvnd/issues/560).
