### ISSUE TITLE
Improved support for IntelliJ Idea

### ISSUE THREAD

**Issue by casonol** [apache/maven-mvnd#664]
this is idea  configuration

![image](https://user-images.githubusercontent.com/49889567/177709569-b2ada208-0ce2-41f7-a787-18f6008255c8.png)

then, you should change maven-mvnd  source lib,
![image](https://user-images.githubusercontent.com/49889567/177709949-5f7e6b08-5df7-49c3-80b0-ab7aa7fbd399.png)
for lib Add to  
 (slf4j-api-1.7.32.jar,  slf4j-api.license, maven-slf4j-provider-3.8.4.jar ) (Available from the maven lib )

In this case, MAVEN in IDEA is using MVND to download dependencies,

If you do not add these three lib(slf4j-api-1.7.32.jar,  slf4j-api.license, maven-slf4j-provider-3.8.4.jar), the IDEA download dependency will report an error,  java.lang.NoClassDefFoundError: org/slf4j/Logger  at org.jetbrains.idea.maven

**Comment by casonol** [comment]
I hope maven-mvnd can be integrated into IDEA. Just as IDEA naturally supports Maven.
then.  advice  

Add three dependencies
 ` maven-slf4j-api-1.7.32. jar, slf4j-api.license, maven-slf4j-provider 3.8.4.jar ` into maven-mvnd-0.8.0 source code  for lib package To support IDEA 2022.1.3 . 

Thank you very much, You can try it
 In this way,  maven-mvnd-0.8.0 is used to replace apache-maven-3.8.6 in idea-2022-1.3 work

**Comment by Resunny** [comment]
This method may not use mvnd, but use the mvn that comes with mvnd.

**Comment by gnodet** [comment]
> This method may not use mvnd, but use the mvn that comes with mvnd.

The maven layout contained in mvnd is not a stock maven layout, so when you launch maven using the `mvn/bin/mvn` script, it will look like maven, but will use some components from mvnd.  However, there will be no daemon used, so no caching, classloader reuse, etc...
