### ISSUE TITLE
can mvnd support remote daemon?

### ISSUE THREAD

**Issue by walnut-tom** [apache/maven-mvnd#665]
for example: 
   the deamon use -Dmvnd.bind=127.0.0.1:1234
   the client use -Dmvnd.demon=127.0.0.1:1234

**Comment by ppalaga** [comment]
Currently, it is not possible. There is some related discussion in https://github.com/apache/maven-mvnd/issues/496.
Adding the config params for a fixed port is doable.
If you really want to run daemon on a remote machine, you'd also have to figure out how to share your workspace with that machine.

**Comment by walnut-tom** [comment]
Is it possible to send workspace content to daemon like docker build？

**Comment by gnodet** [comment]
> Is it possible to send workspace content to daemon like docker build？

No.
