### ISSUE TITLE
Exception in thread "main" java.io.UncheckedIOException: java.nio.charset.MalformedInputException: Input length = 1

### ISSUE THREAD

**Issue by meiMingle** [apache/maven-mvnd#667]

**Comment by meiMingle** [comment]
Fortunately I have solved this problem. The reason is that UTF-8, GBK and other encodings are mixed in our project. My solution is to modify the configuration in the mvnd/conf/mvnd.properties file as follows
`mvnd.jvmArgs=-Dfile.encoding=UTF-8`

**Comment by ppalaga** [comment]
Happy to hear that you found your way @meiMingle!
