### ISSUE TITLE
release .tar.gz format precompiled binary archives 

### ISSUE THREAD

**Issue by gzm55** [apache/maven-mvnd#668]
Now until the 0.8.0 version, only .zip format packages is released. It is better to also release .tar.gz format like [maven](https://maven.apache.org/download.cgi)

**Comment by gnodet** [comment]
The official download location is hosted at the ASF:
  https://downloads.apache.org/maven/mvnd/0.8.0/

**Comment by gzm55** [comment]
@gnodet in the official download, there are no pre-build binaries in .tar.gz format. can we publish both types of  binary packages in the future releases?

**Comment by gnodet** [comment]
Sure

**Comment by gzm55** [comment]
is it possible to also publish to the central, like [apache-maven](https://search.maven.org/artifact/org.apache.maven/apache-maven/3.8.6/pom) ?

**Comment by gzm55** [comment]
> Sure

hi @gnodet,  in staging [0.8.1](https://dist.apache.org/repos/dist/dev/maven/mvnd/0.8.1/) there are no *.tar.gz format binaries

**Comment by gnodet** [comment]
It should be fixed with https://github.com/apache/maven-mvnd/commit/5dce72ef331ce017fb4c023f0f978ef692d1557a
