### ISSUE TITLE
Deployed timestamped snapshot version does not change

### ISSUE THREAD

**Issue by jglick** [apache/maven-mvnd#672]
```bash
mvn deploy
# edit some file
mvn deploy
```

(3.8.6) on a `*-SNAPSHOT` project using `nexus-staging-maven-plugin` will deploy snapshots with two different versions (`…-1` and `…-2`), as expected. But

```bash
mvnd deploy
# edit some file
mvnd deploy
```

(0.7.1) seems to redeploy the same timestamped version (`…-1`). Maybe whatever inside Maven holds a consistent version number across reactor modules (recently added) is improperly being cached?

**Comment by gnodet** [comment]
Fwiw, the `nexus-staging-maven-plugin` uses very old maven api, I would advise to switch to the standard deploy plugin instead.
Also a way to reproduce the problem would be required to identify where the problem comes from.

**Comment by jglick** [comment]
> the `nexus-staging-maven-plugin` uses very old maven api

OK, then unclear where fault may lie. Timestamped snapshots are always a mess anyway. CC @stephenc @jtnord

> switch to the standard deploy plugin

Not an option if you need to automate interactions with Nexus I am afraid—opening a staging repository, grouping changes, closing it, promoting it to release.

> a way to reproduce the problem

Anyway it seems I cannot reproduce on demand.
