### ISSUE TITLE
mvnd not extends parent properties？

### ISSUE THREAD

**Issue by 1013461195** [apache/maven-mvnd#674]
i use `mvnd clean install` prompt my "'dependencies.dependency.version' for com.product.fs:sdk:jar must be a valid version but is '${product-fs.version}'. @ line 53, column 22", but parent properties has this value

**Comment by 1013461195** [comment]
mvnd version info.
![image](https://user-images.githubusercontent.com/23392657/185069192-5cfb70a1-8139-43de-b553-0c4ffaaf4dd6.png)

mvnd.properties

java.home=$JAVA_HOME/bin
maven.settings=/Volumes/Data/maven/apache-maven-3.5.0/conf/settings.xml
mvnd.maxHeapSize=8G
mvnd.minHeapSize=512M
mvnd.threads=12
mvnd.minThreads=1

**Comment by ppalaga** [comment]
Would you please share the pom.xml where this is happening and its parent?

**Comment by 1013461195** [comment]
![image](https://user-images.githubusercontent.com/23392657/192210714-f0500b36-fd2d-4a2b-9548-dbf3a49327b8.png)
![image](https://user-images.githubusercontent.com/23392657/192210760-1d5023de-82f9-4826-8dff-895a1e484501.png)
![image](https://user-images.githubusercontent.com/23392657/192210808-bef7e0bc-a8b8-4344-941f-9d637627f73f.png)

if properties is parent of parent, will throw this exception
