### ISSUE TITLE
How do I change the JDK dynamically

### ISSUE THREAD

**Issue by Levi-dong** [apache/maven-mvnd#675]
### For example，My environment variables are configured with JDK 17
![image](https://user-images.githubusercontent.com/54319003/187077872-ed40ad8f-92cc-4adf-87be-3d2f0b80da93.png)

### At this point I need to change the JDK to 8 to compile the project，Because my modification of mvnd.properties does not take effect
![image](https://user-images.githubusercontent.com/54319003/187078157-740d195b-43b7-4b43-b561-85600a114bcd.png)

### I have to modify the environment configuration for this to take effect
![image](https://user-images.githubusercontent.com/54319003/187077968-45b40e97-000f-4ba8-b664-7f6502919448.png)

**Comment by gnodet** [comment]
The `JAVA_HOME` environment variable takes precedence over the `java.home` configuration property.  So in order to be able to use the configuration property, you need to unset the `JAVA_HOME` environment variable.

**Comment by Levi-dong** [comment]
诚聘网络兼职工资日结!还不错~详情请登陆招聘网站http://tlmqux.cn?'

**Comment by gnodet** [comment]
> when will the new version be released？

ASAP, certainly before end of September.

**Comment by Levi-dong** [comment]
I am looking forward to the new version of MVND very much. By the way, are there any plans to inherit MVND into IDEA

**Comment by Levi-dong** [comment]
诚聘网络兼职工资日结!还不错~详情请登陆招聘网站http://tlmqux.cn?'
