### ISSUE TITLE
Console coloring is off when artifact download is under way

### ISSUE THREAD

**Issue by cstamas** [apache/maven-mvnd#685]
Easy to reproduce: just invoke mvnd (I did it on maven-resolver, but I guess any project will do) and use `-Dmaven.repo.local=foo` to force build to download....

When download is happening (1st build), the output is WHITE (not green). -- more precisely, color is quickly going white-ok, kinda vibrating.

When download is NOT happening (ie. 2nd build using that param above): colorization is OK

**Comment by gnodet** [comment]
The 3 blocks of the following code are not consistent wrt to the project id colouring:
https://github.com/apache/maven-mvnd/blob/1ec11ab3481f21284c820774d5ac4d05a4001176/common/src/main/java/org/mvndaemon/mvnd/common/logging/TerminalOutput.java#L767-L790
