### ISSUE TITLE
can't use system environment variable?

### ISSUE THREAD

**Issue by 1013461195** [apache/maven-mvnd#693]
execute `mvnd clean` `mvnd -version`,tip me 'Could not get a real path from path $JAVA_HOME'
![image](https://user-images.githubusercontent.com/23392657/191907149-8459df31-e109-4ff9-9662-d3049f483a1c.png)

**Comment by gnodet** [comment]
Environment properties are supported using an `env.` prefix, so you may try with
```
java.home=${env.JAVA_HOME}
```

**Comment by 1013461195** [comment]
thanks, but still can't read system env,
![截屏2022-10-09 11 51 57](https://user-images.githubusercontent.com/23392657/194737121-d277028f-5dbb-4a16-94a9-8b714e9c131b.png)
default read ${pwd}/bin/java?

**Comment by 1013461195** [comment]
my from code source 'org.mvndaemon.mvnd.client.DaemonParameters.javaHome' find use env value is '${JAVA_HOME}'. but 'org.mvndaemon.mvnd.client.DaemonParameters.loadProperties' tofirst insert 'env.', last result ${JAVA_HOME} = env.${JAVA_HOME}.
![截屏2022-10-09 15 24 44](https://user-images.githubusercontent.com/23392657/194743642-48066c73-5eb1-42b7-88b9-f050d35c77d8.png)

**Comment by shenjianeng** [comment]
yeah， can't read system env.

but you can use that：

```java
// org.mvndaemon.mvnd.client.DaemonParameters#javaHome
public Path javaHome() {
        final Path result = value(Environment.JAVA_HOME)
                .orLocalProperty(provider, suppliedPropertiesPath())
                .orLocalProperty(provider, localPropertiesPath())
                .orLocalProperty(provider, userPropertiesPath())
                .orLocalProperty(provider, globalPropertiesPath())
                .orSystemProperty()
                .orEnvironmentVariable()
                .or(new ValueSource(
                        description -> description.append("java command"), DaemonParameters::javaHomeFromPath))
                .orFail()
                .cache(provider)
                .asPath();
        try {
            return result.toRealPath();
        } catch (IOException e) {
            throw new RuntimeException("Could not get a real path from path " + result);
        }
    }
```

remove config file ，

use SystemProperty : `mvnd clean deploy -Dmaven.test.skip=true -Ptest -Djava.home=/opt/jdk-11.0.17+8/`
