### ISSUE TITLE
SimpleAppender omits stacktraces

### ISSUE THREAD

**Issue by oehme** [apache/maven-mvnd#696]
The [SimpleAppender](https://github.com/apache/maven-mvnd/blob/874e26cfe829b35ad6b510fe398939ed26eb3a66/daemon/src/main/java/org/mvndaemon/mvnd/logging/internal/SimpleAppender.java#L45) is designed to work like slf4j-simple, but it does not print any stacktraces. This is because it uses an unitialized `ThrowableProxyConverter`. This class has a `lengthOption` setting, which is 0 after instantiation, meaning that it will print 0 stack frames. This field is initialized to Integer.MAX_VALUE in the converter's [start method](https://github.com/qos-ch/logback/blob/master/logback-classic/src/main/java/ch/qos/logback/classic/pattern/ThrowableProxyConverter.java#L51), which is assumed to be called before it is used. 

My suggestion would be to use [ThrowableProxyUtil.asString](https://github.com/qos-ch/logback/blob/master/logback-classic/src/main/java/ch/qos/logback/classic/spi/ThrowableProxyUtil.java#L76) instead.

**Comment by ppalaga** [comment]
Thanks for the report and suggestion, @oehme. Would you like to send a PR by any chance?

**Comment by oehme** [comment]
Thanks for fixing this so quickly!
