### ISSUE TITLE
maven dependency plugin missing pom: mvnd gives error <=> stock mvn warning

### ISSUE THREAD

**Issue by taclano** [apache/maven-mvnd#731]
Hi,

In our project we are trying to use mvnd to speed up our build.

We use the maven dependency plugin to fetch from a remote repository some files ( yaml-files ), these artifacts do not contain a pom remotely. Which I know is not good :( 

With mvnd this causes an error during the build.
With stock mvn this causes only a warning.

Is this the expected behavior ?

Thanks in advance

Version used:
jdk11
mvn => 3.8.6
mvnd => 0.8.2 with mvn 3.8.6

**Comment by ppalaga** [comment]
Could you please be more specific about the error you see? 

What would be the way for others to reproduce the problem?

**Comment by gnodet** [comment]
@taclano could you provide a reproducer ?

**Comment by Swastik-123** [comment]
I am not able to understand the problem,
what is the problem?

**Comment by gnodet** [comment]
I'm closing, please reopen if needed.
