### ISSUE TITLE
Is it possible to print the version of the plugin

### ISSUE THREAD

**Issue by zhaoyunxing92** [apache/maven-mvnd#745]
I especially like this project, I want to know the plugin version at compile time

```log
➜  mvnd clean package -Dmaven.test.skip=true -Dmvnd.debug=true
Building java-agent  daemon: aa845462  threads used/hidden/max:   6/0/11  progress: 194/200  97%  time: 12:19
:apm-spring-cloud-gateway-3.x-plugin maven-shade-plugin:shade @ default
:apm-spring-cloud-gateway-2.1.x-plugin maven-shade-plugin:shade @ default
:apm-spring-cloud-gateway-2.0.x-plugin maven-shade-plugin:shade @ default
:apm-shenyu-2.4.x-plugin          maven-shade-plugin:shade @ default
:apm-resttemplate-4.3.x-plugin    maven-shade-plugin:shade @ default
```

**Comment by ppalaga** [comment]
I would not mind making it configurable, keeping the current behavior as a default. Contributions welcome!

**Comment by gnodet** [comment]
In relation to [MNG-7618](https://issues.apache.org/jira/browse/MNG-7618), I think it could be a good enhancement to switch the display to `pluginPrefix:version:goal` so that we end up with the same display as `maven-4.0.0-alpha-3`.

**Comment by gnodet** [comment]
<img width="726" alt="image" src="https://user-images.githubusercontent.com/84022/205443254-727df289-e26b-4ffb-9662-d75b83bd8755.png">
