### ISSUE TITLE
1.0.0-m1 slower than 0.8.2

### ISSUE THREAD

**Issue by ppalaga** [apache/maven-mvnd#758]
When building Camel Quarkus with these changes https://github.com/apache/camel-quarkus/pull/4355 in place using

```
mvnd clean install -Dquickly
```

1.0.0-m1 is slower than 0.8.2 by more than 10 seconds.

At the first sight the initial scanning of Maven modules takes much longer. It is ~9 seconds with 0.8.2, but ~19 sec with 1.0.0-m1.

Is this expected, @gnodet ?

**Comment by ppalaga** [comment]
Scanning for projects... takes ~10 seconds even when I am in a directory where there is just a single project.

**Comment by gnodet** [comment]
> Scanning for projects... takes ~10 seconds even when I am in a directory where there is just a single project.

That's https://issues.apache.org/jira/browse/MNG-7646

**Comment by gnodet** [comment]
> When building Camel Quarkus with these changes [apache/camel-quarkus#4355](https://github.com/apache/camel-quarkus/pull/4355) in place using
> 
> ```
> mvnd clean install -Dquickly
> ```
> 
> 1.0.0-m1 is slower than 0.8.2 by more than 10 seconds.
> 
> At the first sight the initial scanning of Maven modules takes much longer. It is ~9 seconds with 0.8.2, but ~19 sec with 1.0.0-m1.
> 
> Is this expected, @gnodet ?

I'm aware of the problem, and no this is not really acceptable imho.  I raised [MNG-7647](https://issues.apache.org/jira/browse/MNG-7647).

**Comment by mthmulders** [comment]
> even when I am in a directory where there is just a single project.

Do you mean a directory that is part of a multi-module project, but has no child modules? Or do you mean a directory that has a single project, i.e. not part of multi-module project?

**Comment by ppalaga** [comment]
> > even when I am in a directory where there is just a single project.
> 
> Do you mean a directory that is part of a multi-module project, but has no child modules? 

Yes, exactly this.

**Comment by mthmulders** [comment]
> Yes, exactly this.

Thanks for clarifying.

I'm wondering if there's a measurable difference if you disable build/consumer POM decoupling. From [MNG-6656](https://issues.apache.org/jira/browse/MNG-6656), it should be possible to disable that with `-Dmaven.experimental.buildconsumer=true`. Is that something you could try, please?

**Comment by gnodet** [comment]
I haven't pinpoint the exact problem, however mind 1.0.0-m1 is noticeably slower than 0.8.2.  More significant, running `mvn foo` (so that all projects are parsed but no plugin is executed) was expectedly faster with mind 0.8.2 than maven 3.8.6, but mvn 1.0.0-m1 is slower than maven 4.0.0-alpha-3.
This clearly points toward a problem in mvnd 1.0.0-m1 imho...
