### ISSUE TITLE
`source <(mvnd --completion bash)` stopped working in 0.9.0 

### ISSUE THREAD

**Issue by ppalaga** [apache/maven-mvnd#785]
When issuing 

```
source <(mvnd --completion bash)
```

the completion script appears in the console, but the completion is not sourced. 

Similarly, when piping the output of `--completion bahs` to `wc` the count is zero

```
mvnd --completion bash | wc
[the whole completion script here]

      0       0       0
```

Workaround: adding `2>&1` makes it work:

```
mvnd --completion bash 2>&1 | wc
    358    1259   20910
```

**Comment by gnodet** [comment]
The upgrade to JLine must be the cause. JLine and mvnd now better supports `out` and `err` streams.
I think the line https://github.com/apache/maven-mvnd/blob/e10aecd5f790307e4e0a4ec8938e8ca9d0fb6f5d/client/src/main/java-mvnd/org/mvndaemon/mvnd/client/DefaultClient.java#L223
should be changed to use `Message.out(xxx)` to force the usage of the output stream.
