### ISSUE TITLE
Support maven 3.9.0

### ISSUE THREAD

**Issue by mikomatic** [apache/maven-mvnd#788]
Hello team and thank you for the great project !

It would be great to have a version supporting Maven 3.9.0 (https://maven.apache.org/docs/3.9.0/release-notes.html) before targeting 4.0.0. (which seems present in the main branch).

This way we could benefit from improvements and usage of the [maven-build-cache-extension](https://github.com/apache/maven-build-cache-extension).

Cheers !

**Comment by gnodet** [comment]
See https://github.com/apache/maven-mvnd/tree/mvnd-0.10.x ...

**Comment by delanym** [comment]
choco still thinks v0.8.2 is the latest. Should I be using another source?

**Comment by johanjanssen** [comment]
@delanym choco isn't updated automatically, it needs to be updated manual. Feel free to create a PR for https://github.com/johanjanssen/ChocolateyPackages/tree/master/mvndaemon

**Comment by Tholian** [comment]
Hi everybody,
am I missing something or ist version 0.10.0 not released yet.
I am interested in using the maven build cache extension with mvnd :-)

**Comment by gnodet** [comment]
@Tholian the last release is 1.0.0-m7, see https://github.com/apache/maven-mvnd/releases
