### ISSUE TITLE
Custom settings file not found

### ISSUE THREAD

**Issue by stefanzilske** [apache/maven-mvnd#839]
I have a `settings.xml` and a `maven.config`, which references the settings file with the `-s` option file in a central directory. I symlink the `maven.config` to the `.mvn/` of my project.

`mvnd` cannot build the project anymore, it keeps telling me that the settings file cannot be found. `mvn` itself can build it.

I am using `mvnd` 1.0-m6 darwin-aarch64 native client.

Any hint is appreciated!

**Comment by stefanzilske** [comment]
Hm, this might actually be an issue with Maven 3.9.1 🤔

**Comment by brundabharadwaj** [comment]
> Hm, this might actually be an issue with Maven 3.9.1 🤔
Hi @stefanzilske 
I am not sure if any other file is being referred here, I recently downloaded maven 3.9.1 and I am able to see settings.xml in the conf folder.. if u are taking about .m2 repo's settings.xml , then it would be a custom defined one and will not be present. it needs to be configured by the user.
![image](https://user-images.githubusercontent.com/49773125/235343829-05eb4c80-190c-488a-829e-85d573944637.png)

**Comment by gnodet** [comment]
@stefanzilske do you have any more info ?

**Comment by yanivnahoum** [comment]
@stefanzilske just guessing here - does your maven.config file adhere to the [new format required by maven 3.9.x](https://github.com/apache/maven-site/pull/380)?
One arg per line? So for example this:
`--threads 4`
becomes:
```
--threads
4
```

**Comment by stefanzilske** [comment]
@yanivnahoum yes that's the issue. I even came across the change with Maven 3.9 but I didn't grasp that it was per argument and not per flag. Thanks a lot for pointing that out!
