### ISSUE TITLE
mvnd does not recognize -Dmaven.test.skip=true

### ISSUE THREAD

**Issue by suddenlyyo** [apache/maven-mvnd#854]
[ERROR] Unknown lifecycle phase ".test.skip=true". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix
>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize
, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, proce
ss-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, packa
ge, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site
, site, post-site, site-deploy. -> [Help 1]

**Comment by ppalaga** [comment]
If this is in PowerShell, then using double quotes might help: `"-Dmaven.test.skip=true"`. 
BTW, `"-Dmaven.test.skip"` should be equivalent.

**Comment by suddenlyyo** [comment]
Thanks you

**Comment by finviman** [comment]
In zsh, `mvnd clean install -Prelease -Dmaven.test.skip=true ` can be run, but the test is still running

**Comment by ppalaga** [comment]
> In zsh, `mvnd clean install -Prelease -Dmaven.test.skip=true ` can be run, but the test is still running

Could you please open a new issue with a minimal reproducer?
