### ISSUE TITLE
After opening debug, I compile and produce A daemon A for the first time. After completion, the second compilation generates a new daemon B. What should I do if I want to reuse the first daemon A for the second compilation

### ISSUE THREAD

**Issue by Min-200** [apache/maven-mvnd#855]
After opening debug, I compile and produce A daemon A for the first time. After completion, the second compilation generates a new daemon B. What should I do if I want to reuse the first daemon A for the second compilation

**Comment by gnodet** [comment]
Some options lead to incompatible daemons.  Debugging is one of them, as the JVM either starts with debugging or not, it cannot be turned on/off at runtime, so once you have two daemons running (one with debug, another without), no other daemon should be started.

**Comment by Min-200** [comment]
1.我打开了配置文件的debug开关 mvnd.debug = true
2.我执行的mvnd的编译命令，mvnd clean package ,生成了守护进程A,构建是成功的
3.我再次执行mvnd clean pakage，守护进程不是A，而是新建了一个B

**Comment by Min-200** [comment]
Do you see what's wrong with this, that my goal is to debug and use the same daemon for both my first and second builds
