### ISSUE TITLE
mvnd  The new command is not convenient to use

### ISSUE THREAD

**Issue by qf8505** [apache/maven-mvnd#864]
mvnd Cannot use Maven default plugin ，Deploying a project requires modifying commands，Maybe there are a lot of projects，How to rename mvnd  to mvn

**Comment by gnodet** [comment]
I'm using the following myself:
```
mvn-or-mvnd() {
  local mvnd=`unalias -a && command -v mvnd`
  if [[ -x "$mvnd" ]]; then
    "$mvnd" "$@"
    return $?
  fi

  command mvn "$@"
}

alias mvn="mvn-or-mvnd"
```

**Comment by ppalaga** [comment]
@qf8505 you may use the alias suggested by @gnodet or find another way specific to your operating system. Anyway both are beyond the scope of this project.
