### ISSUE TITLE
Is this project interested in sponsoring?

### ISSUE THREAD

**Issue by uweschaefer** [apache/maven-mvnd#871]
My employer (http://prisma-capacity.eu) has a budget for sponsoring OSS Projects, and i was wondering, if it made sense to suggest to sponsor mvnd. 
I am aware that mvnd by now is an Apache Project and the Apache Foundation has sponsors.  What i do not know, if they use the money to fund infra&legal&org resources only, or if the money "trickles down" to particular projects.

Sponsoring through github or opencollective or similar platforms is thinkable for us.

**Comment by gnodet** [comment]
> My employer (http://prisma-capacity.eu) has a budget for sponsoring OSS Projects, and i was wondering, if it made sense to suggest to sponsor mvnd. I am aware that mvnd by now is an Apache Project and the Apache Foundation has sponsors. What i do not know, if they use the money to fund infra&legal&org resources only, or if the money "trickles down" to particular projects.
> Sponsoring through github or opencollective or similar platforms is thinkable for us.

The money does not go down to particular projects...

**Comment by gnodet** [comment]
A nice way would be to get involved if you have some (human) resources to spare...
