### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.mvndaemon.mvnd.nativ.CLibrary

### ISSUE THREAD

**Issue by misaya98** [apache/maven-mvnd#872]
mvnd version : 0.9.1
jdk version: 
openjdk version "11.0.16" 2022-07-19 LTS
OpenJDK Runtime Environment Zulu11.58+15-CA (build 11.0.16+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.58+15-CA (build 11.0.16+8-LTS, mixed mode)

error:
`PS C:\Users\33156> mvnd
java.lang.NoClassDefFoundError: Could not initialize class org.mvndaemon.mvnd.nativ.CLibrary`

**Comment by TobiX** [comment]
Was there ever a version 0.9.1? Anyways, that is rather old, you should probably try 1.0-m7
