### ISSUE TITLE
mvnd 0.9.0 "destroys" the console

### ISSUE THREAD

**Issue by OLibutzki** [apache/maven-mvnd#884]
After running any mvnd command with 0.9.0 `arrow-up` doesn't work anymore to get the history commands. Instead of the previous command, `^[[A` is printed.

The problem does not exist in the latest 1.0.0 milestone and in 0.8.2.

OS: Windows 10 & 11

**Comment by GitPopcorn** [comment]
I got the same issue, and in fact this problem was solved after `1.0-m6-39/40`, seems it only affect in the version range `0.9.0` to `1.0.0-m4`.

Maybe you can solve this by update your mvnd.

If for a short time usage to mvnd `0.9.0` or `1.0.0-m4`, you can manually run `Ctrl + C` to clear the wrong print like '^[[A', and then run `CMD` or `sh`, `bash` to restore the command line after this issue happend.

**Comment by OLibutzki** [comment]
Yes, I can use 1.0.0. Usally I use Chocolatey to install mvnd. Is it possible to use 1.0.0 milestones with choco, too?

**Comment by GitPopcorn** [comment]
> Yes, I can use 1.0.0. Usally I use Chocolatey to install mvnd. Is it possible to install 1.0.0 milestones with choco, too?

Em... I try it but could only install mvnd up to 0.9.0 with Chocolatey...
Maybe the team just publish release version to Chocolatey repository, not the milestone versions.
That does be bothered.

**Comment by gnodet** [comment]
@OLibutzki  @GitPopcorn  The release process has changed a bit with recent releases.  If someone can provide a script that would automatically publish the release to chocolatey somehow, it could be integrated in https://github.com/apache/maven-mvnd/blob/master/build/release-publish.sh

**Comment by OLibutzki** [comment]
Afaik, @johanjanssen provided the choco packages so far. Maybe he can help?

**Comment by johanjanssen** [comment]
I think Chocolatey doesn't support beta/milestone version information in their tags. So to solve this I think I would need to create a new Chocolatey package with a different id, something like mvnd-beta. Or are there other ways?

Next to that I already indicated that I want to stop maintaining the Chocolatey package, as I don't use them myself anymore. So if someone wants to take over, let me know. I'm happy to maintain it until the end of the year, but after that I won't do it anymore.

**Comment by OLibutzki** [comment]
In my opinion the best option is to include the choco publication in the mvnd release process - similar to homebrew and sdkman.

**Comment by aalmiray** [comment]
JReleaser can certainly help. As @johanjanssen mentioned the use of tags is tricky. I know for a fact that M and RC are treated specially, don't know about BETA and ALPHA. 

Moreover, as Johan has states he'll no longer support the choco package someone else must take on the task.

**Comment by OLibutzki** [comment]
As mvnd 1.0.0 has been relased this issue can be closed.
