### ISSUE TITLE
memory leak at com.sun.tools.javac.util.SharedNameTable$NameImpl

### ISSUE THREAD

**Issue by clebertsuconic** [apache/maven-mvnd#897]
I found a leak with com.sun.tools.javac.util.SharedNameTable$NameImpl

I have been building this with artemis build. But I suspect this is not related to anything on my project. But I will list it here in case it's something hitting only my project:

to reproduce this:

find the mvnd daemon:

```
jps -v | grep mvnd
```

start a check-leak capturing: (https://github.com/check-leak/check-leak)

```
java -jar check-leak-0.12-SNAPSHOT.jar remote --report out-report --sleep 1000 --pid <the-pid>
```

(or if you don't like the fancy graphs... just monitor the number of instances through memory histograms.. which is pretty much what I'm doing on check-leak.. I'm just generating the fancy reports).

start the artemis build:

```
git clone https://github.com/apache/activemq-artemis.git
mvnd clean install -DskipTests=true
```

(you might want to do that once before starting the capturing of the histograms as the firs build will download a bunch of stuff from maven repo)

open ./out-report/index.html

Sort it by number of increases...

you will find the com.sun.tools.javac.util.SharedNameTable$NameImpl on the list of growing objects.

you will see that number of objects will keep growing forever.. if you build 10 times.. you get 10X the number of objects... for my build it's adding about 10K instances on every run.

**Comment by clebertsuconic** [comment]
![image](https://github.com/apache/maven-mvnd/assets/750514/fd3d2980-2301-43b1-aafa-13b41d51ac29)

**Comment by clebertsuconic** [comment]
first build 10K, second build 20K... this build.. 30k ^^^

**Comment by clebertsuconic** [comment]
and just to give it a context on the version being used:


```

lebertsuconic@MacBook-Pro out % mvnd --version
Apache Maven Daemon (mvnd) 1.0-m7 darwin-amd64 native client (b2ef5d81997adbcdb72dc8c5603722538fa641fe)
Terminal: org.jline.terminal.impl.PosixSysTerminal with pty org.jline.terminal.impl.jansi.osx.OsXNativePty
Apache Maven 3.9.3 (21122926829f1ead511c958d89bd2f672198ae9f)
Maven home: /usr/local/Cellar/mvnd/1.0-m7-m39/libexec/mvn
Java version: 11.0.8, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
```

**Comment by rmannibucau** [comment]
While ant is calling `javac` it will cache ~32k `Name` instances so maybe bypassing this module would help

**Comment by clebertsuconic** [comment]
I've tried it with the plexus update, by updating my maven compiler to a snapshot and that fixed the issue:
![image](https://github.com/apache/maven-mvnd/assets/750514/990b1adc-7eeb-4e6e-a189-24725e8fb530)
