### ISSUE TITLE
 Non-resolvable parent POM

### ISSUE THREAD

**Issue by HDHXTM** [apache/maven-mvnd#905]
mvnd version: mvnd 0.8.1(1.0-m8 have the same error )
java:1.8.0

I am using mvnd to build a project：
![image](https://github.com/apache/maven-mvnd/assets/74095069/bd45cc42-0d35-4235-9440-34b20f87d21d)
on windows, all mvnd command are ok.

in linux:

```
[root source]# /usr/share/mvnd/bin/mvnd clean
[INFO] Processing build on daemon 9d18c480
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.roncoo:roncoo-education-common:23.0.0-RELEASE: com.roncoo:roncoo-education:pom:23.0.0-RELEASE was not found in http://maven.aliyun.com/nexus/content/groups/public during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of nexus-aliyun has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 7, column 13
[FATAL] Non-resolvable parent POM for com.roncoo:roncoo-education-feign:23.0.0-RELEASE: com.roncoo:roncoo-education:pom:23.0.0-RELEASE was not found in http://maven.aliyun.com/nexus/content/groups/public during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of nexus-aliyun has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 7, column 13
[FATAL] Non-resolvable parent POM for com.roncoo:roncoo-education-gateway:23.0.0-RELEASE: com.roncoo:roncoo-education:pom:23.0.0-RELEASE was not found in http://maven.aliyun.com/nexus/content/groups/public during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of nexus-aliyun has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 7, column 13
[FATAL] Non-resolvable parent POM for com.roncoo:roncoo-education-service:23.0.0-RELEASE: com.roncoo:roncoo-education:pom:23.0.0-RELEASE was not found in http://maven.aliyun.com/nexus/content/groups/public during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of nexus-aliyun has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 7, column 13
 @
[ERROR] The build could not read 4 projects -> [Help 1]
```

but `/usr/share/mvnd/mvn/bin/mvn clean` is ok

![image](https://github.com/apache/maven-mvnd/assets/74095069/f3264e28-aed6-4544-8eef-5b948146416d)

![image](https://github.com/apache/maven-mvnd/assets/74095069/de6c0ce8-68a5-4b99-992a-d9f44b223f03)
![image](https://github.com/apache/maven-mvnd/assets/74095069/a17e3d2f-4355-4ab0-a901-a41b65c089d1)

**Comment by HDHXTM** [comment]
my mvnd.properties:

mvnd.keepAlive = 500 ms
mvnd.minHeapSize = 512M
mvnd.maxHeapSize = 4G
maven.settings=/usr/share/mvnd/mvn/conf/settings.xml

Other settings are the default values.

/usr/share/mvnd/mvn/conf/settings.xml：

<settings xmlns="http://maven.apache.org/SETTINGS/1.2.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.2.0 https://maven.apache.org/xsd/settings-1.2.0.xsd">
    <pluginGroups>
    </pluginGroups>
    <proxies>
    </proxies>
    <servers>
    </servers>
    <mirrors>
        <mirror>
            <id>nexus-aliyun</id>
            <mirrorOf>central</mirrorOf>
            <name>Nexus aliyun</name>
            <url>http://maven.aliyun.com/nexus/content/groups/public</url>
        </mirror>
    </mirrors>
    <profiles>
    </profiles>
</settings>

**Comment by ppalaga** [comment]
It is strange that mvnd is trying to resolve the parent from a remote repository given it is a part of the build. I assume you execute the build from the top directory, where the com.roncoo:roncoo-education pom is located?

Does the same problem occur when you start with a fresh daemon (after killing the old ones with `mvnd --stop`)?

Does anything change when you remove all `com.roncoo:*` artifacts from your local maven repository?

**Comment by HDHXTM** [comment]
> It is strange that mvnd is trying to resolve the parent from a remote repository given it is a part of the build. I assume you execute the build from the top directory, where the com.roncoo:roncoo-education pom is located?
> 
> Does the same problem occur when you start with a fresh daemon (after killing the old ones with `mvnd --stop`)?
> 
> Does anything change when you remove all `com.roncoo:*` artifacts from your local maven repository?

![image](https://github.com/apache/maven-mvnd/assets/74095069/1ab3583a-1d8c-4970-aec5-7547623bef73)
it is ok!

I am running mvnd in jenkins. Jenkins may build multiple projects at the same time. if run `mvnd --stop` , will other build tasks be stopped? What is the correct usage?

**Comment by ppalaga** [comment]
`mvnd` is primarily an interactive tool for Java developers. It was not designed for Jenkins and similar environments. When doing it anyway, you should consider that deamon re-use may cause serious build reproducibility issues. Please read more in other issues, e.g. here: https://github.com/apache/maven-mvnd/issues/704 To overcome the reproducibility issue, but still profit from parallel builds and sane console output, you may want to try `mvnd.sh` with the `-Dmvnd.noDaemon` flag. Check `mvnd --help` for more info.
