### ISSUE TITLE
How long will it take to support packaging and running in Jenkins?

### ISSUE THREAD

**Issue by ErQire** [apache/maven-mvnd#906]
May I ask the developer a question? I think it would be very interesting and important if we could build and execute in Jenkins. The Maven packaging in the original version is very slow, so it would be great to know which version will support the use of Jenkins and whether it can be used in a production environment.

**Comment by ppalaga** [comment]
`mvnd` is primarily an interactive tool for Java developers. It was not designed for Jenkins and similar environments. When doing it anyway, you should consider that deamon re-use may cause serious build reproducibility issues. Please read more in other issues, e.g. here: https://github.com/apache/maven-mvnd/issues/704 To overcome the reproducibility issue, but still profit from parallel builds and sane console output, you may want to try `mvnd.sh` with the `-Dmvnd.noDaemon` flag. Check `mvnd --help` for more info.
