### ISSUE TITLE
[help] how can I determine whether my source tree supports parallel builds?

### ISSUE THREAD

**Issue by immadolf** [apache/maven-mvnd#907]
Hey guys, the README states, "If your source tree does not support parallel builds, use the -T1 flag on the command line to make your build sequential." 

So, how can I determine whether my source tree supports parallel builds?

**Comment by cstamas** [comment]
You can try plain Maven and use -T x and you will end up with warnings on console, if your build contains any plugin that does not support MT builds.

**Comment by immadolf** [comment]
Thank you for your generous response. @cstamas

**Comment by ppalaga** [comment]
The easiest way IMO is to try and see. You can find some common issues listed around here: https://peter.palaga.org/2023/05/21/mvnd-maven-daemon.html#common_issues
