### ISSUE TITLE
Split mvnd for Maven 3.x and 4.x support

### ISSUE THREAD

**Issue by gnodet** [apache/maven-mvnd#973]
The [upgrade to Maven 4.0-beta-1](https://github.com/gnodet/mvnd/commit/f62be5664a218b3cbe7cdba0b797621bee5a8e18) cannot be done easily (slf4j upgraded from 1 to 2, jline replaces jansi, etc...).
Now is the time to split mvnd again to accommodate the increasing discrepancies between Maven 3 and 4.
I've created:
  * https://github.com/apache/maven-mvnd/tree/mvnd-1.x
  * https://github.com/apache/maven-mvnd/tree/mvnd-2.x

The first one will get the upgrade to 3.9.7 when out, the second one aims to be merged into master.
The plan is to rebase both branches on top of current master asap.

@ppalaga @cstamas any objections ?

**Comment by cstamas** [comment]
None. Go for it
