### ISSUE TITLE
If Maven Daemon executes in 0.2s, the summary output might be printed too early

### ISSUE THREAD

**Issue by bmarwell** [apache/maven-mvnd#995]
Hi,

at a demo at JCON, our build ran in 0.2s (using the cache extension).
The Summary output at the end was not the last to be printed; mvnd was not done printing other entries from the buffer yet, so I had to scroll up for the project summary.

This does usually not happen, because usually it takes 0.6 seconds to complete.
So, there is a timing issue.

Maven Daemon should wait at least until the buffer has been emptied to the console.

Will try to grab a screenshot.

**Comment by codespearhead** [comment]
@bmarwell Can you close it as not planned then?

![](https://i0.wp.com/user-images.githubusercontent.com/7584089/169088905-112804b4-ad7f-4bf0-b4f9-0b7d01e6a18e.png?w=583&ssl=1)

**Comment by bmarwell** [comment]
@pedro: I wanted to see first if anyone encountered the same problem.

Since this seems not to be the case, I will close it.
